# Generated by Django 3.0.6 on 2020-05-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.CharField(choices=[('Developer', 'Developer'), ('UX-designer', 'UX-designer'), ('Front-end Designer', 'Front end designer'), ('Database handler', 'Database handler'), ('Back-end developer', 'Back-end developer'), ('Project management', 'Project management'), ('Xyz', 'Xyz')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CreateContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('as a developer', 'as a developer'), ('as a designer', 'as a designer'), ('as a documentation team', 'as a documentation team')], max_length=25)),
                ('resume', models.FileField(upload_to='resumes')),
                ('contribution', models.CharField(choices=[('Developer', 'Developer'), ('UX-designer', 'UX-designer'), ('Front-end Designer', 'Front end designer'), ('Database handler', 'Database handler'), ('Back-end developer', 'Back-end developer'), ('Project management', 'Project management'), ('Xyz', 'Xyz')], max_length=30)),
                ('contributed', models.BooleanField(default=False)),
            ],
        ),
    ]
