# Generated by Django 3.0.6 on 2020-05-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_remove_createcontributor_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createcontributor',
            old_name='contribution',
            new_name='role',
        ),
    ]
