# Generated by Django 3.0.6 on 2020-05-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_auto_20200506_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontributor',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.Contribution'),
        ),
    ]
