# Generated by Django 3.0.6 on 2020-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0004_auto_20200506_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontributor',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
