# Generated by Django 3.0.6 on 2020-05-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0005_auto_20200506_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontributor',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('UX-designer', 'UX-designer'), ('Front-end Designer', 'Front end designer'), ('Database handler', 'Database handler'), ('Back-end developer', 'Back-end developer'), ('Project management', 'Project management'), ('Xyz', 'Xyz')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
