# Generated by Django 3.0.6 on 2020-05-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0006_auto_20200507_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontributor',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('UX-designer', 'UX-designer')], max_length=50),
        ),
    ]
