# Generated by Django 3.0.6 on 2020-05-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0007_auto_20200507_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontributor',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
