# Generated by Django 3.0.6 on 2020-05-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0008_auto_20200507_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontributor',
            name='role',
            field=models.CharField(choices=[('as a developer', 'as a developer'), ('as a designer', 'as a designer'), ('as a documentation team', 'as a documentation team')], max_length=50),
        ),
    ]
