# Generated by Django 3.0.6 on 2020-05-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0010_auto_20200507_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcontributor',
            name='resume',
        ),
    ]
