# Generated by Django 3.0.6 on 2020-05-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0011_remove_createcontributor_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontributor',
            name='role',
            field=models.CharField(choices=[('developer', 'as a developer'), ('designer', 'as a designer'), ('documentation team', 'as a documentation team')], max_length=25),
        ),
    ]
