# Generated by Django 3.0.6 on 2020-05-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0015_auto_20200509_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createcontributor',
            old_name='about_you',
            new_name='about',
        ),
    ]
