# Generated by Django 3.0.6 on 2020-05-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0017_auto_20200509_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcontributor',
            name='profession',
        ),
    ]
