# Generated by Django 3.0.8 on 2020-07-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0018_remove_createcontributor_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontributor',
            name='about',
            field=models.CharField(max_length=255),
        ),
    ]
